### PR TITLE
Upstream updates

### PR DESCRIPTION
**Pull request by astro**
There have been breaking changes in svd2rust and the cortex-m crate. I re-ran svd2rust. Unfortunately, this drops all of the manual improvements.

### CODE REVIEW

**Comment by astro** [comment]
Here's more on the motivation behind the new I/O model: http://blog.japaric.io/brave-new-io/

**Comment by dkarwowski** [comment]
Ill likely take a look at this tomorrow or sometime during the weekend, and regenerate with the customized patch.

If you want, the patched svd is checked in under the dev branch and you can try regenerating with that, too.

**Comment by astro** [comment]
Sorry, but svd2rust is missing SPI1 with the changes:

```sh
stm32f429x $ svd2rust --target cortex-m -i STM32F429x.svd
error: No register SPI1 in peripheral SPI1
note: run with `RUST_BACKTRACE=1` for a backtrace
```

BTW:
```diff
diff --git STM32F429x.svd STM32F429x.svd
index 7550930..95e9702 100644
--- STM32F429x.svd
+++ STM32F429x.svd
@@ -13297,7 +13297,7 @@ xs:noNamespaceSchemaLocation="CMSIS-SVD_Schema_1_1.xsd">
                   <description>Next transfer is CRC</description>
                   <value>1</value>
                 </enumeratedValue>
-              </enumeratedValue>
+              </enumeratedValues>
             </field>
             <field>
               <name>DFF</name>
@@ -13323,7 +13323,7 @@ xs:noNamespaceSchemaLocation="CMSIS-SVD_Schema_1_1.xsd">
               <bitOffset>10</bitOffset>
               <bitWidth>1</bitWidth>
               <enumeratedValues derivedFrom="SPI1.CR1.BIDIOE.ENABLER">
-              </enumeratedvalues>
+              </enumeratedValues>
             </field>
             <field>
               <name>SSM</name>
```

**Comment by astro** [comment]
No pressure, just a reminder. :-) Thanks in advance!

**Comment by astro** [comment]
Nevermind, I have switched to crate [stm32f429](https://crates.io/crates/stm32f429) which has appeared in the meanwhile. :-)

**Pull request closed without merging**
